# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Designs\add_edit_show_information_group_name_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 270)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(540, 70))
        Dialog.setMaximumSize(QtCore.QSize(540, 270))
        Dialog.setSizeGripEnabled(False)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 521, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.line_edit_group_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_edit_group_name.setObjectName("line_edit_group_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_edit_group_name)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(200, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_save_group_name = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_save_group_name.setObjectName("btn_save_group_name")
        self.horizontalLayout_2.addWidget(self.btn_save_group_name)
        self.btn_cansle_group_name = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_cansle_group_name.setObjectName("btn_cansle_group_name")
        self.horizontalLayout_2.addWidget(self.btn_cansle_group_name)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.table_widget_contact_group_name = QtWidgets.QTableWidget(self.formLayoutWidget)
        self.table_widget_contact_group_name.setObjectName("table_widget_contact_group_name")
        self.table_widget_contact_group_name.setColumnCount(0)
        self.table_widget_contact_group_name.setRowCount(0)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.table_widget_contact_group_name)
        self.label_contact_this_group_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_contact_this_group_name.setObjectName("label_contact_this_group_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_contact_this_group_name)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Group Name"))
        self.btn_save_group_name.setText(_translate("Dialog", "Save"))
        self.btn_cansle_group_name.setText(_translate("Dialog", "Cansle"))
        self.label_contact_this_group_name.setText(_translate("Dialog", "Contacts this Group Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
