# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Designs\add_edit_show_information_contact_book_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(541, 181)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 521, 168))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.line_edit_first_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_edit_first_name.setObjectName("line_edit_first_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_edit_first_name)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.line_edit_last_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_edit_last_name.setObjectName("line_edit_last_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_edit_last_name)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.line_edit_phone_number = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_edit_phone_number.setMaxLength(11)
        self.line_edit_phone_number.setObjectName("line_edit_phone_number")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_edit_phone_number)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.line_edit_email = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_edit_email.setObjectName("line_edit_email")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_edit_email)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.combo_box_group_name = QtWidgets.QComboBox(self.formLayoutWidget)
        self.combo_box_group_name.setObjectName("combo_box_group_name")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.combo_box_group_name)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(200, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_save_contact_book = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_save_contact_book.setObjectName("btn_save_contact_book")
        self.horizontalLayout_2.addWidget(self.btn_save_contact_book)
        self.btn_cansle_contact_book = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_cansle_contact_book.setObjectName("btn_cansle_contact_book")
        self.horizontalLayout_2.addWidget(self.btn_cansle_contact_book)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "First Name"))
        self.label_2.setText(_translate("Dialog", "Last Name"))
        self.label_3.setText(_translate("Dialog", "Phone Number"))
        self.label_4.setText(_translate("Dialog", "Email"))
        self.label_5.setText(_translate("Dialog", "Group Name"))
        self.btn_save_contact_book.setText(_translate("Dialog", "Save"))
        self.btn_cansle_contact_book.setText(_translate("Dialog", "Cansle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
